bin_dir: "/data_center_01/pipeline/gutMicrobiome_v1.0/snakemake"
clean_reads_list: "02.taxon/clean_reads.list"
clean_reads_dir: "01.clean_reads"
NCBI_Bacteria: "/data_center_06/Database/NCBI_Bacteria/20160825/database/bacteria_database.list"
#NCBI_Bacteria: "/data_center_11/DNA_Data/Taxon_ref_Database/NCBI_Bacteria/v1.0_20180627/summary/fasta.list"
NCBI_Archaea: "/data_center_06/Database/NCBI_Archaea/20160525/database/archaea_database.list"
#NCBI_Archaea: "/data_center_11/DNA_Data/Taxon_ref_Database/NCBI_Archaea/v1.0_20180627/summary/fasta.list"
NCBI_Fungi: "/data_center_06/Database/NCBI_Fungi/20160601/database/fungi_database.list"
#NCBI_Fungi: "/data_center_11/DNA_Data/Taxon_ref_Database/NCBI_Fungi/v1.0_20180627/summary/fasta.list"
NCBI_Virus: "/data_center_06/Database/NCBI_Virus/20160615/database/viral.database.list"
#NCBI_Virus: "/data_center_11/DNA_Data/Taxon_ref_Database/NCBI_Virus/v1.0_20180627/summary/fasta.list"
references: "Bacteria,Archaea,Fungi,Virus"
alignmet_parse: "/data_center_01/pipeline/huangy/metagenome/database/alignment_parse.py"
species_abundance_profiler: "/data_center_01/pipeline/huangy/metagenome/database/species_abundance_profiler.py"
check: "/data_center_01/pipeline/gutMicrobiome_v1.0/snakemake/alignBacterial/pyscript/checkerr.py"
python_version: "/data_center_03/USER/huangy/soft/MAIN/anaconda2/bin/python2.7"
